server:
  port: 8084
spring:
  cloud:
    gateway:
      routes:
        - id: courses_route
          uri: http://localhost:8082
          predicates:
            - Path=/courses/**
        - id: users_route
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
